services : 
  - docker

before_install :
  - docker build -t vishalgwalani/react-test -f ./client/Dockerfile.dev ./client

script : 
    - docker run -e CI=true vishalgwalani/react-test npm test

after_success : 
  - docker build -t vishalgwalani/multi-client ./client
  - docker build -t vishalgwalani/multi-nginx ./nginx
  - docker build -t vishalgwalani/multi-server ./server
  - docker build -t vishalgwalani/multi-worker ./worker  
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vishalgwalani/multi-client
  - docker push vishalgwalani/multi-nginx
  - docker push vishalgwalani/multi-server
  - docker push vishalgwalani/multi-worker
  